SocioGhibli/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

groups/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "groups"

urlpatterns = [
    path("", views.ListSocioGhibliGroupView.as_view(), name="all"),
    path("new/", views.CreateSocioGhibliGroupView.as_view(), name="create"),
    path("posts/in/<slug>/", views.SingleSocioGhibliGroupView.as_view(), name="single"),
    path("join/<slug>/", views.JoinSocioGhibliGroupView.as_view(), name="join"),
    path("leave/<slug>/", views.LeaveSocioGhibliGroupView.as_view(), name="leave")
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.SocioGhibliPostList.as_view(), name="all"),
    path("new/", views.SocioGhibliCreatePost.as_view(), name="create"),
    path("by/<username>",views.SocioGhibliUserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.SocioGhibliPostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.SocioGhibliDeletePost.as_view(), name="delete")
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse
import misaka

current_user = get_user_model()
register = template.Library()


class SocioGhibliGroup(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=False, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(current_user, through="SocioGhibliGroupMember")

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["name"]

class SocioGhibliGroupMember(models.Model):
    group = models.ForeignKey(SocioGhibliGroup, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(current_user, related_name="user_groups", on_delete=models.CASCADE)
    favourite_quote = models.CharField(max_length=255, blank=True, default='')

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ("group", "user")

groups/forms.py
from django import forms
from . import models

class SocioGhibliGroupForm(forms.ModelForm):
    class Meta:
        model = models.SocioGhibliGroup
        fields = ("name", "description")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form_input_field_custom list-group-item"}),
            "description": forms.Textarea(attrs={"class": "form_input_field_custom list-group-item"}),
        }

groups/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, RedirectView
from django.contrib import messages
from django.db import IntegrityError
from .models import SocioGhibliGroup, SocioGhibliGroupMember
from .forms import SocioGhibliGroupForm

class CreateSocioGhibliGroupView(LoginRequiredMixin, CreateView):
    form_class = SocioGhibliGroupForm
    model = SocioGhibliGroup
    template_name = "groups/group_form.html"

class SingleSocioGhibliGroupView(DetailView):
    model = SocioGhibliGroup
    context_object_name = "group"
    template_name  = "groups/group_detail.html"

class ListSocioGhibliGroupView(ListView):
    model = SocioGhibliGroup
    template_name = "groups/group_list.html"

class JoinSocioGhibliGroupView(LoginRequiredMixin, RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(SocioGhibliGroup, slug=self.kwargs.get("slug"))
        try:
            SocioGhibliGroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, "Warning, already a member!")
        else:
            messages.success(self.request, "You are now a member!")
        
        return super().get(request, *args, **kwargs)

class LeaveSocioGhibliGroupView(LoginRequiredMixin, RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})
    
    def get(self, request, *args, **kwargs):
        try:
            membership = SocioGhibliGroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get("slug")
            ).get()
        except SocioGhibliGroupMember.DoesNotExists:
            messages.warning(self.request, "Sorry you are not in this group!")
        else:
            membership.delete()
            messages.success(self.request, "You have left the group!")
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static 'groups/css/styles.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block title %}Group{% endblock %}

{% block pregroup %}
  <div class="row">
    <div class="col-md-4">
      <h2 class="aria-font">{{ group.name }}</h2>
      <p class="aria-font">Total number of members: {{ group.members.count }}
        {% if user in group.members.all %}
          <a href="{% url 'groups:leave' slug=group.slug %}" class="ml-2 btn btn-sm btn-warning">
            Leave
          </a>
        {% else %}
          <a href="{% url 'groups:join' slug=group.slug %}" class="ml-2 btn btn-sm btn-dark">
            Join Group
          </a>
        {% endif %}
      </p>
    </div>
  </div>

{% endblock %}

{% block group_content %}
  <div class="row">
    <div class="col-md-12">
      {% if group.posts.count == 0 %}
        <h2>No posts yet!</h2>
      {% else %}
        {% for post in group.posts.all %}
          <div class="mb-3">
            {% include "posts/_post.html" with post=post hide_delete=True %}
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap5 %}

{% block title %} New{% endblock %}
{% block group_content %}
  <h2>Create New Group</h2>
  <form action="{% url 'groups:create' %}" method="post" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
  </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block title %}Groups{% endblock %}

{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2>
          Welcome Back!
          <a href="{% url 'posts:for_user' username=user.username %}">
            @{{ user.username }}
          </a>
        </h2>
      {% endif %}
      <h2>Groups</h2>
    </div>
    {% if user.is_authenticated %}
      <a href="{% url 'groups:create' %}" class="btn btn-md btn-primary mb-2">
        Create New
      </a>
    {% endif %}
  </div>
{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %}
        <a class="list-group-item mb-2" href="{% url 'groups:single' slug=group.slug %}">
          <h3 class="title list-group-item-heading aria-font">
            {{ group.name }}
          </h3>
          <div class="list-group-item-text container-fluid">
            {{ group.description_html|safe }}
          </div>
          <div class="row">
            <div class="col-md-4">
              <span class="badge aria-font">{{ group.members.count }} member{{ group.members.count|pluralize }}</span>
            </div>
            <div class="col-md-4">
              <span class="badge aria-font">{{ group.posts.count }} post{{ group.posts.count|pluralize }}</span>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}