SocioGhibli/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import SocioGhibliUserAuthenticationForm

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SocioGhibliUserSignup.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', authentication_form=SocioGhibliUserAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.SocioGhibliPostList.as_view(), name="all"),
    path("new/", views.SocioGhibliCreatePost.as_view(), name="create"),
    path("by/<username>",views.SocioGhibliUserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.SocioGhibliPostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.SocioGhibliDeletePost.as_view(), name="delete")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} base {% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="icon" type="image/x-icon" href="{% static 'socioghibli/images/bird.ico' %}">
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/master.css' %}">
        {% block extrahead %}{% endblock %}

    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="{% url 'home' %}">SocioGhibli</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'posts:create' %}">Post /</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'groups:all' %}">Groups /</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'groups:create' %}">Create-Group /</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'groups:all' %}">Groups /</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">Login /</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      <div class="container mycontainer ml-5">
          {% block content %}
          Simo forgot to add content!
          {% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+Wy5QqFjbJ+4Iqz5pO5lFf4M+qt9O5L4h3" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 pl-0">
            <h1 class="display-4">Socio-Ghibly</h1>
            <p class="lead">Welcome to the Ghibli fan social media</p>
        </div>
    </div>
</div>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block title %}Loggedin{% endblock %}
{% block content %}
    <h1 class="display-4">Thanks!</h1>
    <p class="lead">You are now logged in.</p>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block title %}Thanks{% endblock %}
{% block content %}
    <h1 class="display-4">You are awesome!</h1>
    <p class="lead">Come back soon.</p>
{% endblock %}