SocioGhibli/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.SocioGhibliPostList.as_view(), name="all"),
    path("new/", views.SocioGhibliCreatePost.as_view(), name="create"),
    path("by/<username>",views.SocioGhibliUserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.SocioGhibliPostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.SocioGhibliDeletePost.as_view(), name="delete")
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

import misaka
from groups.models import SocioGhibliGroup

current_user = get_user_model()

class SocioGhibliPost(models.Model):
    user = models.ForeignKey(current_user, related_name="posts", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(SocioGhibliGroup, related_name="posts", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message
    
    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"username": self.user.username, "pk": self.pk})
    
    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

posts/forms.py
from django import forms
from .models import SocioGhibliPost

class SocioGhibliCreatePostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = SocioGhibliPost
        widgets ={
            "message": forms.Textarea(attrs={"class": "form_input_field_custom list-group-item"}),
            "group": forms.Select(attrs={"class": "form_input_field_custom list-group-item"})
        }

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.http import Http404
from braces.views import SelectRelatedMixin
from posts.models import SocioGhibliPost
from .forms import SocioGhibliCreatePostForm
from . import models

current_user = get_user_model()

class SocioGhibliPostList(SelectRelatedMixin, ListView):
    model = models.SocioGhibliPost
    select_related = ("user", "group")
    template_name = "posts/post_list.html"

class SocioGhibliUserPosts(ListView):
    model = models.SocioGhibliPost
    template_name = "posts/user_post_list.html"

    # I need to work on this get_queryset and get_context_data. My Custom User is not OK.
    def get_queryset(self):
        try:
            user_instance = current_user.objects.get(username__iexact=self.kwargs.get("username"))
            self.post_user = SocioGhibliPost.objects.filter(user=user_instance).order_by('-created_at')
        except current_user.DoesNotExist:
            raise Http404
        else:
            return self.post_user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        context["user_info"] = {
            "username": self.post_user.first().user.username,
        }
        return context

class SocioGhibliPostDetail(SelectRelatedMixin, DetailView):
    model = models.SocioGhibliPost
    select_related = ["user", "group"]
    queryset = model.objects.select_related("user", "group")
    template_name = "posts/post_detail.html"
    context_object_name = "post"

    def get_queryset(self):
        return self.queryset.filter(user__username__iexact=self.kwargs.get("username"))

class SocioGhibliCreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    form_class = SocioGhibliCreatePostForm
    model = models.SocioGhibliPost
    template_name = "posts/post_form.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class SocioGhibliDeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = models.SocioGhibliPost
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")
    template_name = "posts/post_confirm_delete.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)
    
       

posts/templates/posts/_post.html
<div class="post_media col-md-12 border border-1" style="background-color: rgba(212, 207, 207, 0.9);">
    <h3> {{ post.message_html|safe }} </h3>
    <div class="media-body">
        <h5 class="media-heading">
            <span class="username">
                <a href="{% url 'posts:for_user' username=post.user.username%}">@{{post.user.username}}</a>
            </span>
            <time class="time">
                <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.created_at}}</a>
            </time>
        </h5>

        <div class="media-footer">
            {% if user.is_authenticated and post.user == user%}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                <span class="text-danger icon-label"> Delete </span>
            </a>
            {% endif %}

        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}
{% load static %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static 'posts/css/styles.css' %}">
{% endblock %}

{% block title %} New Post {% endblock %}

{% block content %}
<div class="post-page">
    <div class="container">
            {% block prepost%}{% endblock %}
            {% block post_content%}{% endblock %}
            {% block post_post%}{% endblock %}
    </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<h3> Are you sure you want to delete this post? </h3>
<div class="posts">
    <p>User: {{ post.user.username }}</p>
    <p>post.user: {{ post.user }}</p>
    <p>post: {{ post}}</p>
    {% include "posts/_post.html" with post=object hide_delete=True %}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large">
            Cancel
        </a>
    </form>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" with post=post hide_delete=True%}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap5 %}

{% block post_content%}
    <h3 class="aria-font"> Create a new post</h3>
    <form action="{% url 'posts:create' %}" method="post" id="postForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary btn-large">
    </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block pre_post_content %}
<div class="col-md-4">
    {% if requst.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">
                Your Groups
            </h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_groups %}
                    <li class="group li-with-bullet">
                        <a href="{% url 'groups:single' slug=member_group.group.slug %}"></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">
                All Groups
            </h5>
            <ul class="list-unstyled">
                {% for other_group in get_other_groups %}
                    <li class="group li-with-bullet">
                        <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
                    </li>
                {% endfor %}
            </ul>

        </div>

    </div>

</div>
{% endblock %}

{% block post_content %}
    <div class="col-ml-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}       
    </div>
{%endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
    <h2>All Posts from {{ user_info.username|title }}</h2>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
    {% for post in post_user %}
    {% include "posts/_post.html" %}
    {% endfor %}
</div>
{% endblock %}